In [1]:
import joblib
from nltk.corpus import stopwords
import nltk
import re
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences


In [2]:
df = pd.read_csv("../datasets/personalidades_limpio.csv")


In [3]:
def preprocessing_sentence(sentence):
    stoplist = set(stopwords.words("english"))
    
    
    #quito etiquetas
    sentence = re.sub(r'<[^>]*?>', '',sentence)
    #quito signos de puntuacion
    sentence = re.sub('[^a-zA-Z]', ' ',sentence)
    #quito espacios en blanco
    sentence= re.sub(r'\s+', ' ',sentence)
    #todo minusculas
    sentence = sentence.lower()
    #quitar_string_cortos
    sentence = sentence.split()
    sentence = [x for x in sentence if len(x)>=3]
    sentence = " ".join(sentence)
    #quitar palabras irrelevantes que esten en el stopwords
    sentence = sentence.split()
    sentence = [w for w in sentence if w not in stoplist]
    #convierto sentencia a serie pandas, luego a string de lista como el formato con los que entrenó el modelo
    sentence = pd.Series(str(sentence))
  
    return sentence

In [4]:
r = "With its peppy cast and its brilliant, social media-hued color palette, Freaky never forgets to be anything less than a fun time."

In [5]:
r = preprocessing_sentence(r)


In [6]:
X = df["come"]
y = df["pers"]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [8]:
token = Tokenizer(num_words=4000)  #establezco el número máximo de palabras que se pueden conservar, según la frecuencia de palabras.
token.fit_on_texts(X_train)

In [9]:
X_train = token.texts_to_sequences(X_train)
r = token.texts_to_sequences(r)


In [10]:
r= pad_sequences(r, padding='post', maxlen=100)

In [11]:
modelo = joblib.load('modelo_tree.pkl')

In [12]:
pred = modelo.predict(r)

In [13]:
pred

array([4], dtype=int64)

In [14]:
def prediccion_personalidad(sentence,modelo):
    df = pd.read_csv("../datasets/personalidades_limpio.csv")
    X = df["come"]
    y = df["pers"]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
    token = Tokenizer(num_words=4000)  #establezco el número máximo de palabras que se pueden conservar, según la frecuencia de palabras.
    token.fit_on_texts(X_train)
    X_train = token.texts_to_sequences(X_train)
    sentence = token.texts_to_sequences(sentence)
    sentence= pad_sequences(sentence, padding='post', maxlen=100)
    
    pred = modelo.predict(sentence)
    return pred
    
    
    
    

In [15]:
reli = "With its peppy cast and its brilliant, social media-hued color palette, Freaky never forgets to be anything less than a fun time."


In [16]:
reli = preprocessing_sentence(reli)

In [17]:
prediccion_personalidad(reli,modelo)

array([4], dtype=int64)

In [18]:
res = "A film about a virus-ravaged country under lockdown should be able to hit cogent parallels at will at the moment - but a numbing repetition is sadly the main payout."

In [19]:
res = preprocessing_sentence(res)

In [21]:
prediccion_personalidad(res,modelo)

array([7], dtype=int64)